[package]
name = "server"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "openwecd"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
anyhow = "1.0.104"
base64 = "0.23.1"
buf-read-ext = "0.4.0"
httparse = "1.10.1"
hyper = { version = "1.11.1", features = ["full"] }
itoa = "1.0.18"
libgssapi = { version = "0.11.0", features = ["iov"] }
log = "0.4.34"
mime = "0.3.17"
quick-xml = "0.42.0"
roxmltree = "0.21.1"
tokio = { version = "1.53.1", features = ["full"] }
rdkafka = { version = "0.39.0", features = ["zstd", "libz", "external-lz4", "ssl", "sasl", "gssapi"] }
regex = "1.13.1"
uuid = { version = "1.26.1", features = ["v4", "fast-rng"] }
serde = { version = "1.0.229", features = ["derive", "rc"] }
serde_json = "1.0.151"
async-trait = "0.1.92"
chrono = { version  = "0.4.45", default-features = false, features = ["clock"] }
clap = { version = "4.6.7", features = ["cargo"] }
futures-util = "0.3.34"
xmlparser = "0.13.6"
itertools = "0.15.0"
futures = "0.3.34"
bitreader = "0.3.11"
x509-parser = "0.18.1"
sha1 = "0.11.0"
hex = "0.4.3"
redis = { version = "1.7.0", features = ["tokio-comp", "aio"]}
log4rs = "1.4.0"
log-mdc = "0.1.0"
tokio-util = "0.7.19"
thiserror = "2.0.20"
hyper-util = { version = "0.1", features = ["full"] }
socket2 = "0.6.5"
http-body-util = "0.1"
ppp = "2.3.0"
tokio-rustls = "0.26.5"
strum = { version = "0.28.0", features = ["derive"] }
leon = "3.0.3"
metrics = "0.24.6"
metrics-exporter-prometheus = { version = "0.18.3", features = ["http-listener"] }
url = "2.5.8"
