name: Generate Github release draft

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }} package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: debian-bookworm
            dockerfile: Dockerfile-debian-bookworm
            artifact-name: openwec-deb-bookworm-package
            artifact-path: ./target/debian/*.deb
            deb-suffix: _deb12
          - target: debian-trixie
            dockerfile: Dockerfile-debian-trixie
            artifact-name: openwec-deb-trixie-package
            artifact-path: ./target/debian/*.deb
            deb-suffix: _deb13
          - target: almalinux-9
            dockerfile: Dockerfile-almalinux-9
            artifact-name: openwec-alma-9-package
            artifact-path: ./target/generate-rpm/*.rpm

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Build Docker image
        working-directory: build-pkg
        run: docker build -t openwec-builder:${{ matrix.target }} -f ${{ matrix.dockerfile }} .

      - name: Build Debian package
        if: startsWith(matrix.target, 'debian')
        run: |
          docker run -t -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/SRC \
            --env CARGO_HOME=/SRC/target/.cargo \
            openwec-builder:${{ matrix.target }} \
            sh -c "cargo build --release --locked && \
                   cargo deb --no-build --manifest-path=./common/Cargo.toml"
          for i in ./target/debian/*.deb; do mv "$i" "${i/.deb/${{ matrix.deb-suffix }}.deb}"; done

      - name: Build RPM package
        if: matrix.target == 'almalinux-9'
        run: |
          docker run -t -u $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/SRC \
            --env CARGO_HOME=/SRC/target/.cargo \
            openwec-builder:${{ matrix.target }} \
            sh -c "cargo build --release --locked && \
                   strip -s target/release/openwec{d,} && \
                   cargo generate-rpm --package common \
                     --metadata-overwrite=./common/Cargo.toml \
                     --set-metadata=\"release='1.el9'\""

      - name: Upload package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}

  # Need to select "Read and write permissions" under Actions / General / Workflow Permissions
  release:
    name: Github release draft
    needs: [build]
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
    steps:
      - name: Download debian bookworm package
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: openwec-deb-bookworm-package
      - name: Download debian trixie package
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: openwec-deb-trixie-package
      - name: Download almalinux 9 package
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: openwec-alma-9-package
      - name: Get artifacts names
        id: artifacts_names
        run: |
          echo "U_PKG_DEB_BOOKWORM=$(ls openwec*_deb12.deb)" >> "$GITHUB_OUTPUT" && \
          echo "U_PKG_DEB_TRIXIE=$(ls openwec*_deb13.deb)" >> "$GITHUB_OUTPUT" && \
          echo "U_PKG_ALMA_9=$(ls openwec*el9*.rpm)" >> "$GITHUB_OUTPUT"
      - name: Create draft release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          draft: true
          files: |
            ${{ steps.artifacts_names.outputs.U_PKG_DEB_BOOKWORM }}
            ${{ steps.artifacts_names.outputs.U_PKG_DEB_TRIXIE }}
            ${{ steps.artifacts_names.outputs.U_PKG_ALMA_9 }}
